USE IGSD;

ALTER TABLE IGSDEconomy ADD COLUMN IF NOT EXISTS (logistics_t0_progress   INT   UNSIGNED DEFAULT 0,
												  logistics_t0_multiplier FLOAT          DEFAULT 0.0,
												  logistics_t0_target     INT   UNSIGNED DEFAULT 0,
												  logistics_t1_progress   INT   UNSIGNED DEFAULT 0,
												  logistics_t1_multiplier FLOAT          DEFAULT 0.0,
												  logistics_t1_target     INT   UNSIGNED DEFAULT 0,
												  logistics_t2_progress   INT   UNSIGNED DEFAULT 0,
												  logistics_t2_multiplier FLOAT          DEFAULT 0.0,
												  logistics_t2_target     INT   UNSIGNED DEFAULT 0,
												  logistics_t3_progress   INT   UNSIGNED DEFAULT 0,
												  logistics_t3_multiplier FLOAT          DEFAULT 0.0,
												  logistics_t3_target     INT   UNSIGNED DEFAULT 0,
												  logistics_t4_progress   INT   UNSIGNED DEFAULT 0,
												  logistics_t4_multiplier FLOAT          DEFAULT 0.0,
												  logistics_t4_target     INT   UNSIGNED DEFAULT 0,
												  logistics_t5_progress   INT   UNSIGNED DEFAULT 0,
												  logistics_t5_multiplier FLOAT          DEFAULT 0.0,
												  logistics_t5_target     INT   UNSIGNED DEFAULT 0);
